# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PVH Exercise 1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PVH Exercise 1

  target 'PVH Exercise 1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PVH Exercise 1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
